image: nvcr.io/nvidia/pytorch:21.10-py3
port: 8501
command:
  - /bin/sh
  - '-c'
  - |
    apt-get update -y && apt-get -y install libgl1
    cd /opt/repos/repo
    pip install -r requirements.txt
    streamlit run app.py
models:
  - id: mosz1h7q3cpntkj
    path: /opt/models/pretrained_models
repositories:
  dataset: dsvvvrd9msdm4eo
  mountPath: /opt/repos
  repositories:
    - url: https://github.com/joshua-paperspace/BlendGAN
      name: repo
      ref: main
resources:
  replicas: 1
  instanceType: P5000